from __future__ import annotations

import hashlib
import json
import re
import tomllib
from importlib import metadata
from pathlib import Path
from typing import Any


def build_license_inventory(
    *,
    root: Path,
    output_path: Path,
    notices_path: Path,
    requirements_lock_path: Path,
) -> dict[str, Any]:
    """Inventory every resolved Python and npm package with version, license and source."""
    root = root.resolve()
    python_rows = _python_rows(root / "pyproject.toml")
    npm_rows = _npm_rows(root / "apps" / "web" / "package-lock.json")
    packages = sorted(
        [*python_rows, *npm_rows],
        key=lambda row: (row["ecosystem"], row["name"].casefold(), row["version"]),
    )
    missing_version = sum(not row["version"] for row in packages)
    missing_license = sum(not row["license"] for row in packages)
    missing_source = sum(not row["source"] for row in packages)
    if missing_version or missing_license or missing_source:
        raise ValueError("license inventory contains incomplete package records")

    inventory: dict[str, Any] = {
        "inventory_version": "third-party-inventory-v1",
        "generated_from": {
            "python_project": "pyproject.toml",
            "python_lock": "requirements.lock",
            "npm_lock": "apps/web/package-lock.json",
        },
        "summary": {
            "python_packages": len(python_rows),
            "npm_packages": len(npm_rows),
            "total_packages": len(packages),
            "missing_version": missing_version,
            "missing_license": missing_license,
            "missing_source": missing_source,
        },
        "packages": packages,
    }
    inventory["inventory_hash"] = hashlib.sha256(
        json.dumps(packages, ensure_ascii=True, separators=(",", ":"), sort_keys=True).encode()
    ).hexdigest()

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        json.dumps(inventory, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    requirements_lock_path.write_text(
        "# Generated by `shiftzero build-license-inventory`; verification environment.\n"
        + "\n".join(f"{row['name']}=={row['version']}" for row in python_rows)
        + "\n",
        encoding="utf-8",
        newline="\n",
    )
    notices_path.write_text(_render_notices(inventory), encoding="utf-8", newline="\n")
    return inventory


def _python_rows(pyproject_path: Path) -> list[dict[str, Any]]:
    project = tomllib.loads(pyproject_path.read_text(encoding="utf-8"))
    production = {_requirement_name(value) for value in project["project"]["dependencies"]}
    development = {
        _requirement_name(value)
        for value in project["project"].get("optional-dependencies", {}).get("dev", [])
    }
    excluded = {"pip", "setuptools", "shiftzero-hero002", "wheel"}
    rows: list[dict[str, Any]] = []
    seen: set[tuple[str, str]] = set()
    for distribution in metadata.distributions():
        name = distribution.metadata.get("Name")
        if not name:
            continue
        normalized = _normalize_name(name)
        if normalized in excluded:
            continue
        key = (normalized, distribution.version)
        if key in seen:
            continue
        seen.add(key)
        if normalized in production:
            dependency_group = "production-direct"
        elif normalized in development:
            dependency_group = "development-direct"
        else:
            dependency_group = "resolved-transitive"
        rows.append(
            {
                "ecosystem": "python",
                "name": name,
                "version": distribution.version,
                "license": _python_license(distribution),
                "source": _python_source(distribution, name, distribution.version),
                "dependency_group": dependency_group,
            }
        )
    return sorted(rows, key=lambda row: (row["name"].casefold(), row["version"]))


def _npm_rows(lock_path: Path) -> list[dict[str, Any]]:
    lock = json.loads(lock_path.read_text(encoding="utf-8"))
    root_package = lock["packages"][""]
    production = set(root_package.get("dependencies", {}))
    development = set(root_package.get("devDependencies", {}))
    rows: list[dict[str, Any]] = []
    for package_path, package in lock["packages"].items():
        if not package_path:
            continue
        name = package.get("name") or package_path.rsplit("node_modules/", maxsplit=1)[-1]
        if name in production:
            dependency_group = "production-direct"
        elif name in development:
            dependency_group = "development-direct"
        elif package.get("dev"):
            dependency_group = "development-transitive"
        else:
            dependency_group = "production-transitive"
        license_value = package.get("license")
        if isinstance(license_value, list):
            license_value = " OR ".join(str(value) for value in license_value)
        rows.append(
            {
                "ecosystem": "npm",
                "name": name,
                "version": package.get("version", ""),
                "license": str(license_value or ""),
                "source": package.get("resolved", ""),
                "dependency_group": dependency_group,
            }
        )
    return sorted(rows, key=lambda row: (row["name"].casefold(), row["version"]))


def _python_license(distribution: metadata.Distribution) -> str:
    value = distribution.metadata.get("License-Expression")
    if value:
        return value.strip()
    value = distribution.metadata.get("License")
    if value and "\n" not in value and len(value) <= 160:
        return value.strip()
    classifiers = distribution.metadata.get_all("Classifier", [])
    license_classifiers = [
        classifier.removeprefix("License :: ")
        for classifier in classifiers
        if classifier.startswith("License :: ")
    ]
    return " / ".join(license_classifiers)


def _python_source(distribution: metadata.Distribution, name: str, version: str) -> str:
    project_urls = distribution.metadata.get_all("Project-URL", [])
    preferred = {"source", "source code", "repository", "homepage"}
    for project_url in project_urls:
        label, separator, url = project_url.partition(",")
        if separator and label.strip().casefold() in preferred:
            return url.strip()
    homepage = distribution.metadata.get("Home-page")
    return homepage.strip() if homepage else f"https://pypi.org/project/{name}/{version}/"


def _requirement_name(requirement: str) -> str:
    return _normalize_name(re.split(r"[<>=!~;\[]", requirement, maxsplit=1)[0].strip())


def _normalize_name(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).casefold()


def _render_notices(inventory: dict[str, Any]) -> str:
    summary = inventory["summary"]
    direct = [row for row in inventory["packages"] if row["dependency_group"].endswith("-direct")]
    lines = [
        "# Third-party dependency notices",
        "",
        "This inventory is generated from the installed frozen Python verification environment",
        "and `apps/web/package-lock.json`. Every resolved package has an exact version, declared",
        "license identifier and source URL. The complete transitive inventory is in",
        "`THIRD_PARTY_LICENSES.json`; `requirements.lock` freezes the Python environment.",
        "",
        "## Inventory coverage",
        "",
        f"- Python packages: {summary['python_packages']}",
        f"- npm packages: {summary['npm_packages']}",
        f"- Total resolved packages: {summary['total_packages']}",
        "- Missing versions, licenses or sources: 0",
        "",
        "## Direct dependencies",
        "",
        "| Ecosystem | Package | Exact version | License | Group | Source |",
        "|---|---|---:|---|---|---|",
    ]
    for row in direct:
        values = [
            row["ecosystem"],
            row["name"],
            row["version"],
            row["license"],
            row["dependency_group"],
            row["source"],
        ]
        lines.append("| " + " | ".join(str(value).replace("|", "\\|") for value in values) + " |")
    lines.extend(
        [
            "",
            "## Reproduction and release review",
            "",
            "Regenerate with `shiftzero build-license-inventory` in the project virtual",
            "environment after dependency changes. CI tests require the JSON inventory to cover",
            "every resolved package in both lock sources with no missing metadata.",
            "",
            "License identifiers are an engineering inventory, not legal advice. Before public",
            "release, review attribution, notice-copy and source-offer obligations for the exact",
            "versions recorded in `THIRD_PARTY_LICENSES.json`.",
            "",
        ]
    )
    return "\n".join(lines)
